name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest

    # Setting up the PostgreSQL database
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Healthcheck for PostgreSQL database
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    # All the steps that GitHub Actions checks
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v2

      - name: Install Ruby (.ruby_version)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      
      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: Install Gems
        run: |
          bundle install

      - name: Prepare Database
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rails db:prepare

      - name: Run RSPEC Tests
        # env:
          # PGHOST: localhost
          # PGUSER: postgres
          # PGPASSWORD: postgres
          # RAILS_ENV: test
        run: |
          bundle exec rspec spec