name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest

    # Setting up the PostgreSQL database w/ Health Check
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    # Steps for GitHub Actions
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@main

      - name: Install Ruby (.ruby_version)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      
      - name: Install Dependencies
        run: |
          gem install bundler
          sudo apt install -yqq libpq-dev

      - name: Install Gems
        run: |
          bundle install

      - name: Prepare Database
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rails db:prepare

      - name: Run RSpec Tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rspec spec